micronaut:
    application:
        name: gateway
    server:
        port: 8080
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:192.168.4.163}:${CONSUL_PORT:8500}"